
# Beep thgit e Robot with user input
print("Please enter a character for the eye:")
eye = input()

print("\t\t\t\t\t\t\t\t\t\t\t\t###")
print("\t\t\t\t\t\t\t\t\t\t\t##########")
print(f"\t\t\t\t\t\t\t\t\t\t\t# {eye}   {eye}  #")
print("\t\t\t\t\t\t\t\t\t\t\t#   #    #")
print("\t\t\t\t\t\t\t\t\t\t\t# \\___/  #")
print("\t\t\t\t\t\t\t\t\t\t\t##########")
print("\t\t\t\t\t\t\t\t\t\t\t   +++")
print("\t\t\t\t\t\t\t\t\t\t\t    #")
print("\t\t\t\t\t\t\t\t\t\t ################")
print("\t\t\t\t\t\t\t\t\t\t\t    #")
print("\t\t\t\t\t\t\t\t\t\t\t    #")
print("\t\t\t\t\t\t\t\t\t\t\t    #")
print("\t\t\t\t\t\t\t\t\t\t\t    #")
print("\t\t\t\t\t\t\t\t\t\t\t    #")
print("\t\t\t\t\t\t\t\t\t\t\t   #  #")
print("\t\t\t\t\t\t\t\t\t\t\t  #    #")
print("\t\t\t\t\t\t\t\t\t\t\t #      #")